import { shape, string } from 'prop-types';

export default shape({
  id: string,
  name: string,
  description: string,
  createdBy: string,
  createdAt: string,
  dueTo: string,
  status: string,
  owner: string,
  inputData: string,
  outputData: string,
  priority: string,
  subject: string,
  type: string,
  form: string,
  activatedAt: string,
  skipable: string,
  workItemId: string,
  processId: string,
  processDefinitionId: string,
  parentId: string,
  slaCompliance: string,
  slaDueTo: string,
  potentialOwners: string,
  excludedOwners: string,
  businessAdmins: string,
});
